# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: To Ba Minh Duc (Finn)
title: Full Stack Developer
email: duc.tbmd@gmail.com
website: www.github.com/ductbmd

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: tobaminhduc1
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: duc-to-23b5b6172
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: githubCV
  icon: fas fa-globe
  url: https://ductbmd.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Duc(Finn) and I'm a FullStack Developer. As well as Backend Dev I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and technical skills.

  I am most skilled in: <mark>Java</mark> and <mark>VueJs</mark>

content:
  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Start Up CSupporter
        # link: icorrect.vn
        sub_title: Php Developer
        caption: Jun 2018 - Mar 2019
        quote: >
          Solving problems on learning English. Create awesome applications helps student impove listening, speaking, reading skill.
        description: | # this will include new lines to allow paragraphs
          I was in a team of 5 people (backend, front-end, system). My task is discuss database design, create api for WebApp and MobileApp, write some small tool for admin, teacher to improve efficiency in student management, create landing page for new product.
        content:
      - layout: left
        title: Adsplus Company
        link: adsplus.vn
        sub_title: Java Developer
        caption: Jun 2018 - Mar 2019
        quote: >
          Top 3 biggest Google Partner in Viet Nam. Adsplus is a digital Marketing Agency successfully deployed more than 10,000 communication campaigns for more than 2000 businesses in Vietnam.
        description: | # this will include new lines to allow paragraphs
          I was in a backend team of 3 people. My task is like any other programmer : "coding". Furthermore, I was learn a large amount of business, how a company operates.
          Some project of me in adsplus:
          - Quotation in 5 minutes: A awesome project help sales reduce time create an quotaion from 2-6h to 5-15 minutes. 
          - Customer health score: Put your google ads account input, it will show account's score, Where is the strong, where is the weak, what needs to be improved?
          - Lead pool: A mini CRM for SME company. This project have all base function what company need to take care customer, save contact and history email, sms, call. Plan the campaign remarketing.
          - Sms hero: This is a service of Leadpool. It help other project set api to send sms, config and set permission for api.
          Techstack I use : <mark>Java Spring boot</mark> <mark>Mysql</mark><mark>MongoDb</mark><mark>Microservices</mark>
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/ductbmd
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ha Noi University of Science and Technology
        caption: 2016 - 2020
        sub_title: Software Engineer
        quote: >
          Established in 1956, Hanoi University of Science and Technology (HUST) is the first prestigious and influential multidisciplinary technical university in Vietnam.
        description: | # this will include new lines to allow paragraphs
          During my time at HUST I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          Here there were more resources available to me than I ever could have imagined. I studied new languages, algorithms, compilers, higher mathematics, all with pretty much the same fascination that drove me as a kid. And it was here that I learned truly how much there was yet to learn, meet amazing good friends of my life.

          I spent a lot of my free time as a member of the *Bach Khoa Love Book Club* taking on roles such as *Media committee member* and *Enthusiastic Gen 4*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Reading book
      - Gaming
      - Football
      - In the future I want to have a blog of travel and teaching programming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
